services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - .env
    networks:
      - shared-network
    restart: unless-stopped
    depends_on:
      db-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  db-init:
    image: postgres:13-alpine
    networks:
      - shared-network
    env_file:
      - .env
    command: >
      bash -c "
      until PGPASSWORD=$$DB_PASSWORD psql -h $$DB_HOST -U $$DB_USERNAME -d postgres -c 'SELECT 1' > /dev/null 2>&1; do
        echo 'Waiting for PostgreSQL to become available...';
        sleep 1;
      done;

      echo 'PostgreSQL is available, checking if database exists...';

      PGPASSWORD=$$DB_PASSWORD psql -h $$DB_HOST -U $$DB_USERNAME -d postgres -tc \"SELECT 1 FROM pg_database WHERE datname = '$$DB_DATABASE'\" | grep -q 1 ||
      PGPASSWORD=$$DB_PASSWORD psql -h $$DB_HOST -U $$DB_USERNAME -d postgres -c \"CREATE DATABASE $$DB_DATABASE\";

      echo 'Database setup completed successfully';
      "
networks:
  shared-network:
    external: true
    name: orvio-bundl-network
