version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: bundl-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bundl
    volumes:
      - bundl-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: bundl-redis
    ports:
      - "6379:6379"
    command: redis-server --notify-keyspace-events Ex
    volumes:
      - bundl-redis-data:/data
    restart: unless-stopped

volumes:
  bundl-postgres-data:
  bundl-redis-data: 