version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - bundl-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bundl_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bundl-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --notify-keyspace-events Ex
    volumes:
      - redis_data:/data
    networks:
      - bundl-network
    restart: unless-stopped

networks:
  bundl-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: 